name: Showcase
version: 2.0a1
author: narrowtux
description: Item showcasing and visual shop plugin for Bukkit-based Minecraft servers.

main: com.narrowtux.showcase2.ShowcaseMain
softdepend: [NarrowtuxLib]

commands:
  showcase:
    aliases: [sc]
    description: Access to all showcase commands
